# Generated by Django 4.0.6 on 2022-09-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRF', '0002_dept_person_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='salary',
            field=models.IntegerField(default=20000),
        ),
    ]
